//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataRepository
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesHistory
    {
        public int UserId { get; set; }
        public int PublicationId { get; set; }
        public System.DateTime Date { get; set; }
        public int SaleId { get; set; }
        public Nullable<decimal> Amount { get; set; }
    
        public virtual User AspNetUser { get; set; }
        public virtual Publication Publication { get; set; }
    }
}
