//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Report
    {
        public int UserId { get; set; }
        public int ReportedId { get; set; }
        public int Reason { get; set; }
        public string Message { get; set; }
        public int ReportId { get; set; }
    
        public virtual User AspNetUser { get; set; }
        public virtual User AspNetUser1 { get; set; }
        public virtual Report_Reasons Report_Reasons { get; set; }
    }
}
